//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espacio()
        {
            this.Estacionamiento = new HashSet<Estacionamiento>();
        }
    
        public int Esp_ID { get; set; }
        public string Esp_Estado_Uso { get; set; }
        public string Esp_Estado { get; set; }
        public string Esp_Desc { get; set; }
        public int Seg_ID { get; set; }
    
        public virtual Segmento Segmento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estacionamiento> Estacionamiento { get; set; }
    }
}
