//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Park.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamiento
    {
        public int Est_ID { get; set; }
        public int Park_ID { get; set; }
        public int Seg_ID { get; set; }
        public int Esp_ID { get; set; }
        public string Est_Ocupacion { get; set; }
        public int Est_Tiem_Oc { get; set; }
        public decimal Est_Val_Total_tar { get; set; }
        public string Est_Estado { get; set; }
    
        public virtual Espacio Espacio { get; set; }
        public virtual Segmento Segmento { get; set; }
        public virtual Park Park { get; set; }
    }
}
